### ISSUE TITLE
components目录下的vue组件 配置 config 引入原生组件 不能使用原生组件

### ISSUE THREAD

**Issue by huqio** [F-loat/mpvue-config-loader#3]

**Comment by huqio** [comment]
必须在对应的page页面同时 配置 config 引入原生组件 才能使用，为什么？

**Comment by F-loat** [comment]
全局组件在 app.vue 中配置，推荐使用官方支持的写法 [configuration](https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html)
